In [1]:
import cv2 as cv
import numpy as np

In [2]:
img=cv.imread("C:/Users/admin/Pictures/cv/butterfly.jfif")

In [3]:
convimg=cv.cvtColor(img,cv.COLOR_BGR2RGB)

# RESHAPE

In [4]:
resize=convimg.reshape((-5,15))
resize

array([[ 5, 58, 30, ...,  0, 41, 27],
       [ 0, 32, 25, ...,  2, 26, 30],
       [ 4, 25, 30, ...,  4, 25, 28],
       ...,
       [14, 61, 43, ..., 44, 52, 39],
       [52, 57, 37, ..., 15, 36,  0],
       [18, 44,  9, ...,  7, 48, 30]], dtype=uint8)

In [5]:
vec=np.float32(resize)
vec

array([[ 5., 58., 30., ...,  0., 41., 27.],
       [ 0., 32., 25., ...,  2., 26., 30.],
       [ 4., 25., 30., ...,  4., 25., 28.],
       ...,
       [14., 61., 43., ..., 44., 52., 39.],
       [52., 57., 37., ..., 15., 36.,  0.],
       [18., 44.,  9., ...,  7., 48., 30.]], dtype=float32)

## ITERATION TERMINATION CRITERIA

In [6]:
CRITERIA1=(cv.TERM_CRITERIA_EPS+cv.TERM_CRITERIA_MAX_ITER,100,1)

##### CLUSTER CONDITION

In [7]:
k=3
attempts=100

##### K_MEANS CLUSTERING

In [8]:
compactness,label,centre=cv.kmeans(vec,k,None,CRITERIA1,attempts,cv.KMEANS_PP_CENTERS)

In [9]:
center=np.uint8(centre)
center

array([[ 11,  70,  27,   8,  67,  27,   7,  66,  27,   8,  67,  28,  11,
         70,  28],
       [ 71, 131,  17,  71, 131,  16,  70, 131,  15,  72, 132,  16,  72,
        132,  17],
       [159, 178,  31, 166, 184,  33, 168, 185,  33, 165, 183,  32, 158,
        177,  30]], dtype=uint8)

#### FLATTERING AND RESHAPE

In [10]:
res=center[label.flatten()]
res_img=res.reshape((resize.shape))
res_img

array([[11, 70, 27, ..., 11, 70, 28],
       [11, 70, 27, ..., 11, 70, 28],
       [11, 70, 27, ..., 11, 70, 28],
       ...,
       [11, 70, 27, ..., 11, 70, 28],
       [11, 70, 27, ..., 11, 70, 28],
       [11, 70, 27, ..., 11, 70, 28]], dtype=uint8)

In [11]:
cv.imshow("w1",img)
cv.imshow("w2",res_img)
cv.waitKey(0)
cv.destroyAllWindows

<function destroyAllWindows>

In [12]:
segmented_image=cv.pyrMeanShiftFiltering(img,50,40)

In [13]:
cv.imshow("w1",img)
cv.imshow("w3",segmented_image)
cv.waitKey(0)
cv.destroyAllWindows

<function destroyAllWindows>